# Generated by Django 4.0.3 on 2022-05-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textdata', '0002_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
