# Generated by Django 4.0.3 on 2022-06-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textdata', '0006_alter_upload_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='title',
            field=models.CharField(default='News', max_length=30),
        ),
    ]
