# Generated by Django 4.0.3 on 2022-06-30 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True)),
                ('text', models.TextField(blank=True)),
                ('prediction', models.BooleanField(blank=True)),
                ('category', models.CharField(blank=True, choices=[('N-Agr', 'News'), ('Agr', 'Agriculture')], max_length=300)),
            ],
        ),
    ]
